### ISSUE TITLE
Add support for Iframes

### ISSUE THREAD

**Issue by msindwan** [msindwan/mhtml2html#1]
iframes should have corresponding content included with embedded resources

**Comment by sabirahmed121** [comment]
@msindwan : Any chance you tried to add this enhancement?

**Comment by msindwan** [comment]
Hi @sabirahmed121! 

I haven't tried working on this ticket yet but it should hopefully be pretty straightforward. Assuming the mhtml document includes the content of each iframe, this would most likely require updating the converter with a new tag and recursively running through the nested nodes. 

Pull requests are welcome! If not, I'll try to get around to it within the next two weeks :)

**Comment by msindwan** [comment]
This should now be supported starting from v3.0.0! Please include the `convertIframes` option to enable the feature (disabled by default).
