### ISSUE TITLE
How to use this html object? any Idea

### ISSUE THREAD

**Issue by vinodchauhan7** [msindwan/mhtml2html#23]
How can we show the same html page in JS

**Comment by msindwan** [comment]
Hi @vinodchauhan7 with the output, you should be able to render the html document as you normally would. If you're looking to render it on the client via Javascript, you can replace the current document with the new HTML document e.g

```js
document.replaceChild(docGeneratedWithMhtml2html.documentElement, document.documentElement);
```

You could also potentially render it in an iframe
