### ISSUE TITLE
No DOM parser available

### ISSUE THREAD

**Issue by brobles82** [msindwan/mhtml2html#39]
### Description
When running from command line the plugin works perfect, but when running inside my app I get this error `No DOM parser available`

I checked the documentation and the example shows I only have to do ` const html = mhtml2html.convert(data)`

I also tried the other way

with JSDOM and I get this error ` Failed to install path-browserify: pnpm failed to install modules`

**Comment by msindwan** [comment]
Hi @brobles82, to confirm is your app a node js app? You need to explicitly provide a DOM parser if so: https://github.com/msindwan/mhtml2html/blob/master/index.js#L34.

Regarding JSDOM, the issue appears to be something related to browserify. Can you share more details on your app setup?
