### ISSUE TITLE
I wrote a new parser

### ISSUE THREAD

**Issue by benjamingr** [msindwan/mhtml2html#5]
Hey, I just published a fast mhtml parser that converts the mhtml files saved by Chrome to html and allows serving them.

It solves a similar issue to this package - I wanted to know if you want to collaborate.

Namely: I do this differently (I don't go through DOM) and I don't have browser compatibility (as a goal).

Would love feedback and to know if it's relevant to you https://www.npmjs.com/package/fast-mhtml

**Comment by msindwan** [comment]
Hi @benjamingr 

Sorry for the late response. I'm not sure why I didn't get a notification from GitHub.

I'd be happy to take a look at your package! I'm interested in seeing how you've optimized your parser. This package is a little different in that it converts the mhtml to a single html file (with both node and browser compatibility). It would be cool to see if and how these packages could work together.

Let me know if you have any specific ideas in mind
